[package]
name = "brinkokevin/easymacros"
description = "MacroTypes module for the EasyMacros plugin"
license = "MIT"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "MacroTypes.lua", "wally.toml"]
exclude = ["*"]

[dependencies]
